name: random_colored
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  solid_lints: ^0.0.14


flutter:
  
  uses-material-design: true

